<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>eia</string>
		<string>nc</string>
		<string>ngc</string>
		<string>prg</string>
		<string>mpf</string>
	</array>
	<key>name</key>
	<string>G-code</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>\(.*\)</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>flow control operators</string>
			<key>match</key>
			<string>(IF|THEN|AND|OR|WHILE|GOTO|G65|M98|M97)</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comparison operators</string>
			<key>match</key>
			<string>(GT|LT|GE|LE|EQ)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>flow control operators - locations</string>
			<key>match</key>
			<string>(?&lt;=GOTO|DO)\d+</string>
			<key>name</key>
			<string>markup.italic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>functions</string>
			<key>match</key>
			<string>(ABS|ACOS|ASIN|ATAN|COS|LN|EXP|FIX|FUP|MOD|ROUND|SQRT|SIN|TAN)</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variables</string>
			<key>match</key>
			<string>(#\d+)</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>O &amp; N numberes</string>
			<key>match</key>
			<string>([ON]([\d])+)</string>
			<key>name</key>
			<string>storage.type.programnum</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Pre-load tool number</string>
			<key>match</key>
			<string>(?&lt;=([T\d\. ]))([T]([\d\.])+)</string>
			<key>name</key>
			<string>support.function.tool2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Current tool number</string>
			<key>match</key>
			<string>([T]([\d\.])+)</string>
			<key>name</key>
			<string>support.function.tool1</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - alpha component - X</string>
			<key>match</key>
			<string>([X]{1})(?=([\d\.-])*)</string>
			<key>name</key>
			<string>keyword.position.x.identifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - alpha component - Y</string>
			<key>match</key>
			<string>([Y]{1})(?=([\d\.-])*)</string>
			<key>name</key>
			<string>keyword.position.y.identifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - alpha component - Z</string>
			<key>match</key>
			<string>([Z]{1})(?=([\d\.-])*)</string>
			<key>name</key>
			<string>keyword.position.z.identifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - alpha component - I</string>
			<key>match</key>
			<string>([I]{1})(?=([\d\.-])*)</string>
			<key>name</key>
			<string>keyword.position.i.identifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - alpha component - J</string>
			<key>match</key>
			<string>([J]{1})(?=([\d\.-])*)</string>
			<key>name</key>
			<string>keyword.position.j.identifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - alpha component - K</string>
			<key>match</key>
			<string>([K]{1})(?=([\d\.-])*)</string>
			<key>name</key>
			<string>keyword.position.k.identifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - alpha component - A</string>
			<key>match</key>
			<string>([A]{1})(?=([\d\.-])*)</string>
			<key>name</key>
			<string>keyword.position.a.identifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - alpha component - B</string>
			<key>match</key>
			<string>([B]{1})(?=([\d\.-])*)</string>
			<key>name</key>
			<string>keyword.position.b.identifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - alpha component - C</string>
			<key>match</key>
			<string>([C]{1})(?=([\d\.-])*)</string>
			<key>name</key>
			<string>keyword.position.c.identifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - alpha component - U</string>
			<key>match</key>
			<string>([U]{1})(?=([\d\.-])*)</string>
			<key>name</key>
			<string>keyword.position.u.identifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - alpha component - V</string>
			<key>match</key>
			<string>([V]{1})(?=([\d\.-])*)</string>
			<key>name</key>
			<string>keyword.position.v.identifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - alpha component - W</string>
			<key>match</key>
			<string>([W]{1})(?=([\d\.-])*)</string>
			<key>name</key>
			<string>keyword.position.w.identifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - numeric component - X</string>
			<key>match</key>
			<string>(?&lt;=X)([\d\.-])*</string>
			<key>name</key>
			<string>keyword.position.x.value</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - numeric component - Y</string>
			<key>match</key>
			<string>(?&lt;=Y)([\d\.-])*</string>
			<key>name</key>
			<string>keyword.position.y.value</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - numeric component - Z</string>
			<key>match</key>
			<string>(?&lt;=Z)([\d\.-])*</string>
			<key>name</key>
			<string>keyword.position.z.value</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - numeric component - I</string>
			<key>match</key>
			<string>(?&lt;=I)([\d\.-])*</string>
			<key>name</key>
			<string>keyword.position.i.value</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - numeric component - J</string>
			<key>match</key>
			<string>(?&lt;=J)([\d\.-])*</string>
			<key>name</key>
			<string>keyword.position.j.value</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - numeric component - K</string>
			<key>match</key>
			<string>(?&lt;=K)([\d\.-])*</string>
			<key>name</key>
			<string>keyword.position.k.value</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - numeric component - A</string>
			<key>match</key>
			<string>(?&lt;=A)([\d\.-])*</string>
			<key>name</key>
			<string>keyword.position.a.value</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - numeric component - B</string>
			<key>match</key>
			<string>(?&lt;=B)([\d\.-])*</string>
			<key>name</key>
			<string>keyword.position.b.value</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - numeric component - C</string>
			<key>match</key>
			<string>(?&lt;=C)([\d\.-])*</string>
			<key>name</key>
			<string>keyword.position.c.value</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - numeric component - U</string>
			<key>match</key>
			<string>(?&lt;=U)([\d\.-])*</string>
			<key>name</key>
			<string>keyword.position.u.value</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - numeric component - V</string>
			<key>match</key>
			<string>(?&lt;=V)([\d\.-])*</string>
			<key>name</key>
			<string>keyword.position.v.value</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions - numeric component - W</string>
			<key>match</key>
			<string>(?&lt;=W)([\d\.-])*</string>
			<key>name</key>
			<string>keyword.position.w.value</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>feeds &amp; speeds</string>
			<key>match</key>
			<string>(?&lt;= )[FS]([\d\.-])+</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>spindle actuation</string>
			<key>match</key>
			<string>(M(20|30){0,1}(3|4|5)(?!\d))</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>brackets</string>
			<key>match</key>
			<string>(\[|\])</string>
			<key>name</key>
			<string>string.interpolated</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>work coordinates</string>
			<key>match</key>
			<string>^.*G10.*$</string>
			<key>name</key>
			<string>support.function.wcs.write</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>work coordinates</string>
			<key>match</key>
			<string>(G(1){0,1}(5)(2|3|4|5|6|7|8|9)(\.5){0,1})</string>
			<key>name</key>
			<string>support.function.wcs</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>tool change</string>
			<key>match</key>
			<string>(M6)</string>
			<key>name</key>
			<string>support.function.tool.change</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>g codes - movement</string>
			<key>match</key>
			<string>(G[0123] )</string>
			<key>name</key>
			<string>support.function.movement</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.iso6983</string>
	<key>uuid</key>
	<string>e6875107-21f9-449b-bbae-036db969b3d2</string>
</dict>
</plist>
